### ISSUE TITLE
Many kids channels not working

### ISSUE THREAD

**Issue by ghost** [coder-alpha/CcloudTv.bundle#4]
This is a great work :+1: 
I am trying some of the kids channels which are listed under this [list](http://pastebin.com/raw.php?i=rGk2Se1P) but the most of them are not working. 
List of channels under kids category: 
- Channel 60 : working
- Chancel 61 : not working
- Channel 62 : not working
- and the rest are not working as well

**Comment by coder-alpha** [comment]
The plugin will only play channels that work, if they dont work they wont play. If you have a certain issue with the plugin not playing working channel you can keep this issue open.

I will also suggest reading the http://forums.plex.tv/discussion/166602/rel-ccloudtv-channel-iptv/p1 thread for issues and announcements.

Cheers,
CA

**Comment by ghost** [comment]
oh okay, my bad, I thought you had control over channels as well. 
a question regarding the plugin, is it possible to include channel art to be displayed?
for example when I click "Poster view" on plex, there is green background with play icon

**Comment by coder-alpha** [comment]
Channel art/logo will be included with the next version. Currently the pastebin links do not include the art/logo. If you have more suggestions please post here http://forums.plex.tv/discussion/166602/rel-ccloudtv-channel-iptv/p13

Thanks !
