### ISSUE TITLE
"There was a problem playing this item"

### ISSUE THREAD

**Issue by medemi68** [coder-alpha/CcloudTv.bundle#8]
Good afternoon,

I've been trying to get this to work for a bit, still no luck. I've tried it from within the Plex App on my phone, as well as Plex Web, and it almost immediately shows "There was a problem playing this item" as soon as I click on an item to watch.

Is there a specific version of PMS that I need to be using? I looked in the console, and it kept saying 400 Bad Request.

Let me know.

**Comment by miigotu** [comment]
Same problem here, with both 0.20 and 0.19. Happens on every channel, not just some/most.

**Comment by TheDaChicken** [comment]
Try Turning off Direct Stream and Direct Play

**Comment by TheDaChicken** [comment]
Plex, Release a update fix that. Just update to the least version of Plex. It's fixed.

EDIT: Sorry, I had to update the message. I was tired when I created it and it was full of word mistakes.
